### ISSUE TITLE
Use squash merging as the pr merge strategy.

### ISSUE THREAD

**Issue by ChengYueJia** [Sin7Y/olavm#123]
#### What?
There are three pr merge strategies: (normal) merge, squash, rebase.
More info about them on https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github .

#### Why?
1. Clean git logs. As we all know, when someone new a pr, usually, there are more than one commit. Using this strategy can squash many into one.
2. The commit msg will be `Pr title` + `pr num`. We can easy track the pr context of a commit.

* A demo as below:
<img width="520" alt="image" src="https://user-images.githubusercontent.com/108982045/216757328-e33c2678-e38d-4430-8b92-de3d327cc922.png">

#### How?
* Go to `repo->settings->General` 
* Confg the `Pull Requests` like below:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/108982045/216757435-44804a0f-3cc1-4fbd-8574-a9e0fdd6a673.png">

**Comment by spartucus** [comment]
Cool idea, applied the strategy.
