### ISSUE TITLE
thread 'main' panicked at assembler/src/encode.rs:263:18: not match opcode:{

### ISSUE THREAD

**Issue by nihaoqingtuan** [Sin7Y/olavm#159]
I followed the [tutorial](https://github.com/Sin7Y/olavm/blob/main/docs/olavm/ola_manuals.md) to run the asm file and wanted to generate a code file, but this step reported an error:

**$ ola asm --input fib.asm --output fib.code
Input assemble file path: fib.asm
thread 'main' panicked at assembler/src/encode.rs:263:18:
not match opcode:{
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace**

**Comment by nihaoqingtuan** [comment]
fib.asm
`{
  "program": "main:\n.LBL7_0:\n  add r8 r8 4\n  mstore [r8,-2] r8\n  mov r1 10\n  call fib_recursive\n  add r8 r8 -4\n  end\nfib_recursive:\n.LBL8_0:\n  add r8 r8 9\n  mstore [r8,-2] r8\n  mov r0 r1\n  mstore [r8,-3] r0\n  mload r0 [r8,-3]\n  eq r0 r0 1\n  cjmp r0 .LBL8_1\n  jmp .LBL8_2\n.LBL8_1:\n  mov r0 1\n  add r8 r8 -9\n  ret\n.LBL8_2:\n  mload r0 [r8,-3]\n  eq r0 r0 2\n  cjmp r0 .LBL8_3\n  jmp .LBL8_4\n.LBL8_3:\n  mov r0 1\n  add r8 r8 -9\n  ret\n.LBL8_4:\n  mload r0 [r8,-3]\n  not r7 1\n  add r7 r7 1\n  add r1 r0 r7\n  range r1\n  call fib_recursive\n  mstore [r8,-7] r0\n  mload r0 [r8,-3]\n  not r7 2\n  add r7 r7 1\n  add r0 r0 r7\n  mstore [r8,-4] r0\n  mload r0 [r8,-4]\n  range r0\n  mload r1 [r8,-4]\n  call fib_recursive\n  mload r1 [r8,-7]\n  add r0 r1 r0\n  mstore [r8,-5] r0\n  mload r0 [r8,-5]\n  range r0\n  mload r0 [r8,-5]\n  add r8 r8 -9\n  ret\n",
  "prophets": []
}`

**Comment by nihaoqingtuan** [comment]
fib.ola
`contract Fibonacci {

    fn main() {
       fib_recursive(10);
    }

    fn fib_recursive(u32 n) -> (u32) {
        if (n == 1) {
            return 1;
        }
        if (n == 2) {
            return 1;
        }

        return fib_recursive(n -1) + fib_recursive(n -2);
    }

}
`

**Comment by Softcloud88** [comment]
I'm really sorry for the confusion. The reason behind this is that the ola-lang project is entirely open-source, while the olavm project has been open-sourced in stages. This has led to compatibility issues between the latest assembly code compiled from the most recent ola-lang code and the older codebase of olavm. We have plans to fully open-source olavm in the near future, which will address this disparity between the compiler and virtual machine versions.

**Comment by nihaoqingtuan** [comment]
ok.
