### ISSUE TITLE
How to ensure that the program and the proof are bound together

### ISSUE THREAD

**Issue by nihaoqingtuan** [Sin7Y/olavm#160]
I found that the verification command only needs to input a proof file, so how to ensure that the proof received by the verifier is the proof of the given program. Some stark proofs I have learned will include the hash of the program in order to bind the program and the proof.

**Comment by Softcloud88** [comment]
Good question. Our program will generate a table in which the contract's presence at the correct address will be ensured through a hash. Additionally, cross table lookups will be performed between the CPU table and the program table to ensure that all instructions executed by the CPU originate from the correct program. We haven't open-sourced this portion of the code yet, and we expect to have significant updates to our open-source library around the end of September.
